- id: config_pilot_fixture_light
  alias: Config Pilot fixture automation
  trigger:
    - platform: state
      entity_id: input_boolean.config_pilot_fixture
      to: "on"
  action:
    - service: logbook.log
      data:
        name: Config Pilot
        message: Fixture automation triggered.
